baseURL = 'https://www.gigworx.in/'
languageCode = 'en-us'
title = 'Gigworx Staffing Solution'
theme = 'gigworx-theme'
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
